src/Digital/NolimitBundle/Entity/Photo.php
<?php
namespace Digital\NolimitBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Digital\NolimitBundle\Entity\Film;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Photo
 * @ORM\Table(name="photo")
 * @ORM\Entity(repositoryClass="Digital\NolimitBundle\Repository\PhotoRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Photo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @Assert\File(
     *     maxSize = "3M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
      )
     * @ORM\Column(name="url", type="string", length=155, nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;

    private $file;

    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;


    private $path;

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param UploadedFile $file
     * @return Image
     * @internal param string $url
     *
     */
    public function setUrl( $file = null)
    {
        $this->url = $file;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }



    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */

    public function setFile( UploadedFile $file)
    {

        $this->file = $file;

    }
    
    public function getUploadPath() {
        
        return "uploads/".$this->url;
    }
}

src/Digital/NolimitBundle/Controller/DefaultController.php
<?php

namespace Digital\NolimitBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Digital\NolimitBundle\Entity\Film;
use Digital\NolimitBundle\Entity\Categorie;

use Digital\NolimitBundle\Repository\FilmRepository;
use Digital\NolimitBundle\Form\FilmType;



class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
         $em = $this->getDoctrine()->getManager();
        $films = $em->getRepository('DigitalNolimitBundle:Film')->listeDesFilms($request->get('page'));
       
    // Controller Action

    # Count of ALL posts (ie: `20` posts)
    $totalPosts = $films->count();//total de films
    
    
    $limit = 2; //nombre de films par page
    $maxPages = ceil($totalPosts / $limit);
    $thisPage = $request->get('page');


        
        
        return $this->render('DigitalNolimitBundle:Default:index.html.twig',
                compact('films', 'maxPages', 'thisPage'));
    }
    
    public function addAction(Request $request)
    { 

        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);
        //$em = $this->getDoctrine()->getManager();
        if ($form->isSubmitted() && $form->isValid()) {
                  $file = $film->getFile()->getFile();
                  if(!empty($file)){
                   $fileName = $this->get('digital_no_limit.file_uploader')->upload($file);
                   
                  $film->getFile()->setUrl( $fileName);
                   $film->getFile()->setAlt($fileName);
                   }
            $em = $this->getDoctrine()->getManager();
            $em->persist($film);
            $em->flush();
             //dump($request);
            return $this->redirect($this->generateUrl(
                'digital_nolimit_show',
                array('id' => $film->getId())
            ));

        }
        
        return $this->render('DigitalNolimitBundle:Default:add.html.twig', ['form' => $form->createView()]);
    }
     
    public function deleteAction($id)
    { 
        $em = $this->getDoctrine()->getManager();
        $film = $em->getRepository('DigitalNolimitBundle:Film')->find($id);
       
        $em->remove($film);
        $em->flush();
        
        return $this->redirectToRoute('digital_nolimit_homepage');

    }
    
    public function showAction($id)
    {
        $film = $this->getDoctrine()->getRepository('DigitalNolimitBundle:Film')->find(intval($id));

        //dump($book);

        if (!$film) {
            throw $this->createNotFoundException(
                'No film found for id ' . $id
            );
        }
        return $this->render('DigitalNolimitBundle:Default:detail.html.twig', ['film' => $film]);
    }
    
    public function filmsParCategorieAction($id)
    {
        
        
        if (!$id) {
            throw $this->createNotFoundException(
                'No film found for id ' . $id
            );
        }
        $em = $this->getDoctrine()->getManager();
        $films = $em->getRepository('DigitalNolimitBundle:Film')->listeDesFilmsParCategerie($id);
        return $this->render('DigitalNolimitBundle:Default:film-par-categorie.html.twig', ['films' => $films]);
    }
    /**
     * recherche d'un film par titre, categorie,
     * 
     * @param type $id
     * @return type
     * @throws type
     */
    public function rechercheAction()
    {
       $em = $this->getDoctrine()->getManager();
        $films = $em->getRepository('DigitalNolimitBundle:Film')->rechercherFilm("Piège",2);
        
        return $this->render('DigitalNolimitBundle:Default:recherche.html.twig');
    }
}

src/Digital/NolimitBundle/Resources/views/Default/add.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>Ajout des films</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
    {{ form_end(form) }}
    
{% endblock %}

src/Digital/NolimitBundle/Resources/views/Default/detail.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>Detail</h1>
    
    {{ dump(film) }}
{% endblock %}
{# empty Twig template #}

src/Digital/NolimitBundle/Resources/views/Default/edit.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>Edition de film</h1>
{% endblock %}

src/Digital/NolimitBundle/Resources/views/Default/film-par-categorie.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>Genre : {{ films[0].categorie.name}}</h1>
    <h2>Liste des films avec pagination sur catégorie choisie </h2>
    
    <ul class="list-group">
        {% for film in films %}
            <li class="list-group-item">{{ film.titre }}</li>
        {% endfor %}
   </ul>
{% endblock %}
{# empty Twig template #}

src/Digital/NolimitBundle/Resources/views/Default/index.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>List des Films</h1>
    <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Category</th>
                        <th>Photo</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for film in films %}
                    <tr>
                        <td>{{ film.titre }}</td> 
                        <td>{{ film.description |slice(1, 150) }}</td>
                        <td><a href="{{path('digital_nolimit_categorie', {'id':film.categorie.id} )}}">{{ film.categorie }}</a></td>
                       
                        <td>
                            
                            {% set image='uploads/no_image.jpg' %}
                            {% if film.file.url is not empty %}
                                 {% set image=film.file.uploadPath %}
                            {% endif %}
                                <img width="90" height="60" src="{{asset(image)}}" alt="no image"/>
                        <td><a href="{{ path('digital_nolimit_show',{'id':film.id}) }}" class="btn btn-primary">Detail</a></td>
                        <td><a href="{{ path('digital_nolimit_delete',{'id':film.id}) }}" class="btn btn-danger">Supprimer</a></td>
                    </tr>
                    
                    
                    {% endfor %}
                </tbody>
            </table>
                    
        {% if maxPages > 1 %}
<ul class="pagination pagination-sm">
    {# `«` arrow  #}
    <li {{ thisPage == 1 ? 'class="disabled"' }}>
        <a href="{{ path('digital_nolimit_homepage', {page: thisPage-1 < 1 ? 1 : thisPage-1}) }}">«</a>
    </li>

    {# Render each page number #}
    {% for i in 1..maxPages %}
    <li {{ thisPage == i ? 'class="active"' }}>
    <a href="{{ path('digital_nolimit_homepage', {page: i}) }}">{{ i }}</a>
    </li>
    {% endfor %}

    {# `»` arrow #}
    <li {{ thisPage == maxPages ? 'class="disabled"' }}>
        <a href="{{ path('digital_nolimit_homepage', {page: thisPage+1 <= maxPages ? thisPage+1 : thisPage}) }}">»</a>
    </li>
</ul>
{% endif %}

{% endblock %}

src/Digital/NolimitBundle/Resources/views/Default/recherche.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1>Résultats de la recherche</h1>
    
{% endblock %}
{# empty Twig template #}